import type { Property, PropertyTask, Handler, BuildingType, TaskDetail, User } from "./types"

export const MOCK_HANDLERS: Handler[] = [
  { id: "1", name: "室橋", color: "#e6f9f3" }, // 緑系
  { id: "2", name: "山下", color: "#e6f0fc" }, // 青系
  { id: "3", name: "小道", color: "#f3e6fc" }, // 紫系
  { id: "4", name: "赤堀", color: "#fdcaca" }, // 赤系（濃く変更）
]

export const MOCK_BUILDING_TYPES: BuildingType[] = [
  { id: "1", name: "マンション", icon: "🏢" },
  { id: "2", name: "戸建て", icon: "🏠" },
  { id: "3", name: "土地", icon: "🏞️" },
  { id: "4", name: "スポーツジム", icon: "🏋️" },
  { id: "5", name: "アパート", icon: "🏘️" },
]

export const MOCK_PROPERTIES: Property[] = [
  {
    id: "1",
    propertyNumber: 12,
    propertyName: "中川区大当郎",
    roomNumber: "スポーツジム",
    propertyType: "その他",
    characteristic: "通常",
    status: "仲介物件",
    price: 2080,
    companyName: "株式会社ライフリノベーション",
    handlerName: "室橋",
    athomeNumber: "AT001",
    infoSource: "レインズ",
    transactionType: "元付(売)自社",
    keyLocation: "現地キーボックス（1234）",
    publicInfo: "現状有姿での引き渡しとなります。",
    vendorCompanyName: "ライフリノベーション",
    vendorPhone: "090-1111-2222",
    creditorCompanyName: "東海銀行",
    creditorContactPerson: "室橋",
    creditorPhone: "052-123-4567",
    memo: "担当者様、現地確認をお願いします。",
    isArchived: false,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
    createdBy: "1",
  },
  {
    id: "2",
    propertyNumber: 1295,
    propertyName: "岡崎市福岡町",
    roomNumber: "中古戸建",
    propertyType: "戸建て",
    characteristic: "相続",
    status: "仲介物件",
    price: 3580,
    companyName: "株式会社ABC不動産",
    handlerName: "山下",
    athomeNumber: "AT002",
    infoSource: "業者より直接",
    transactionType: "客付(買)",
    isArchived: false,
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-01"),
    createdBy: "2",
  },
  {
    id: "3",
    propertyNumber: 1249,
    propertyName: "グランドメゾン博多",
    roomNumber: "N105号",
    propertyType: "マンション",
    characteristic: "通常",
    status: "業者物件",
    price: 1720,
    companyName: "XYZエステート株式会社",
    handlerName: "小道",
    athomeNumber: "AT003",
    infoSource: "アットホーム",
    transactionType: "元付(売)他社",
    vendorCompanyName: "XYZエステート",
    vendorContactPerson: "赤堀",
    vendorPhone: "080-3333-4444",
    isArchived: false,
    createdAt: new Date("2024-02-10"),
    updatedAt: new Date("2024-02-10"),
    createdBy: "3",
  },
  {
    id: "4",
    propertyNumber: 1333,
    propertyName: "プレセンス広小路東",
    roomNumber: "807号室",
    propertyType: "マンション",
    characteristic: "離婚",
    status: "仲介物件",
    price: 1840,
    companyName: "株式会社DEF不動産",
    handlerName: "赤堀",
    athomeNumber: "AT004",
    transactionType: "元付(売)他社",
    isArchived: false,
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
    createdBy: "4",
  },
  {
    id: "5",
    propertyNumber: 1399,
    propertyName: "ニューブレス久屋大通",
    roomNumber: "205号",
    propertyType: "マンション",
    characteristic: "通常",
    status: "所有物件",
    price: 1500,
    companyName: "株式会社ライフリノベーション",
    handlerName: "室橋",
    athomeNumber: "AT005",
    transactionType: "元付(売)自社",
    vendorCompanyName: "ライフリノベーション",
    isArchived: false,
    createdAt: new Date("2024-02-15"),
    updatedAt: new Date("2025-07-14"),
    createdBy: "1",
    isVacant: true,
    keyPhotoUrl: "https://via.placeholder.com/150/FF0000/FFFFFF?text=KeyPhoto",
  },
  {
    id: "6",
    propertyNumber: 1369,
    propertyName: "新潟県十日町市",
    roomNumber: "古家付土地",
    propertyType: "土地",
    characteristic: "破産",
    status: "販売中止", // Changed from "契約後" to "販売中止"
    price: 33,
    companyName: "株式会社GHI不動産",
    handlerName: "山下",
    athomeNumber: "AT006",
    transactionType: "客付(買)",
    contractDate: new Date("2025-07-14"),
    settlementDate: new Date("2025-09-17"),
    isArchived: false,
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2025-07-14"),
    createdBy: "2",
  },
  {
    id: "7",
    propertyNumber: 1401,
    propertyName: "名古屋市中区栄",
    roomNumber: "マンション",
    propertyType: "マンション",
    characteristic: "通常",
    status: "契約後", // Added a new property with "契約後" status
    price: 4500,
    companyName: "株式会社ABC不動産",
    handlerName: "室橋",
    athomeNumber: "AT007",
    transactionType: "元付(売)自社",
    contractDate: new Date("2025-02-01"),
    settlementDate: new Date("2025-04-15"),
    isArchived: false,
    createdAt: new Date("2025-02-01"),
    updatedAt: new Date("2025-02-20"),
    createdBy: "1",
  },
]

export const MOCK_TASKS: PropertyTask[] = [
  {
    id: "1",
    propertyId: "6",
    propertyNumber: 1369,
    propertyName: "新潟県十日町市",
    companyName: "株式会社GHI不動産",
    handlerName: "山下",
    handlerColor: "#e6f0fc",
    contractDate: new Date("2025-07-14"),
    settlementDate: new Date("2025-09-17"),
    price: 33,
    estimatedSales: "5/5",
    sellerName: "田中太郎",
    buyerName: "鈴木一郎",
    reform: {
      status: "完了",
      completionDate: new Date("2025-08-05"),
    },
    loanProcedure: {
      status: "未手配",
    },
    survey: {
      status: "手配中",
      companyName: "山田測量",
      plannedDate: new Date("2025-08-20"),
    },
    demolition: {
      status: "未手配",
    },
    mortgageCancellation: {
      status: "完了",
      completionDate: new Date("2025-08-15"),
    },
    registration: {
      status: "手配中",
      judicialScrivener: "佐藤法務",
    },
    venueArrangement: {
      status: "完了",
    },
    postProcessing: {
      status: "手配中",
    },
    isCompleted: false,
    createdAt: new Date("2025-07-14"),
    updatedAt: new Date("2025-08-15"),
  },
  {
    id: "2",
    propertyId: "7",
    propertyNumber: 1401,
    propertyName: "名古屋市中区栄",
    companyName: "株式会社ABC不動産",
    handlerName: "室橋",
    handlerColor: "#e6f9f3",
    contractDate: new Date("2025-02-01"),
    settlementDate: new Date("2025-04-15"),
    price: 4500,
    estimatedSales: "80/70",
    sellerName: "佐藤花子",
    reform: { status: "手配中", companyName: "リフォーム太郎", plannedDate: new Date("2025-03-10") },
    loanProcedure: { status: "本申込済", bank: "三菱UFJ銀行" },
    survey: { status: "完了", completionDate: new Date("2025-02-20") },
    demolition: { status: "未手配" },
    mortgageCancellation: { status: "手配中" },
    registration: { status: "手配中", judicialScrivener: "田中司法書士" },
    venueArrangement: { status: "手配中" },
    postProcessing: { status: "手配中" },
    isCompleted: false,
    createdAt: new Date("2025-02-01"),
    updatedAt: new Date("2025-02-20"),
  },
  {
    id: "3",
    propertyId: "8",
    propertyNumber: 1425,
    propertyName: "大阪市北区梅田",
    companyName: "XYZエステート株式会社",
    handlerName: "小道",
    handlerColor: "#f3e6fc",
    contractDate: new Date("2025-02-10"),
    settlementDate: new Date("2025-05-20"),
    price: 6800,
    estimatedSales: "120/100",
    buyerName: "高橋健太",
    reform: { status: "完了", completionDate: new Date("2025-03-15") },
    loanProcedure: { status: "金商契約済" },
    survey: { status: "完了", completionDate: new Date("2025-02-25") },
    demolition: { status: "未手配" },
    mortgageCancellation: { status: "完了", completionDate: new Date("2025-03-05") },
    registration: { status: "手配中", judicialScrivener: "金沢法務" },
    venueArrangement: { status: "完了" },
    postProcessing: { status: "手配中" },
    isCompleted: false,
    createdAt: new Date("2025-02-10"),
    updatedAt: new Date("2025-03-15"),
  },
  {
    id: "4",
    propertyId: "9",
    propertyNumber: 1450,
    propertyName: "横浜市西区みなとみらい",
    companyName: "株式会社DEF不動産",
    handlerName: "赤堀",
    handlerColor: "#fdcaca",
    contractDate: new Date("2025-03-01"),
    settlementDate: new Date("2025-06-10"),
    price: 8200,
    estimatedSales: "150/130",
    reform: { status: "手配中", companyName: "横浜リフォーム", plannedDate: new Date("2025-04-15") },
    loanProcedure: { status: "本申込済", bank: "みずほ銀行" },
    survey: { status: "手配中", companyName: "横浜測量", plannedDate: new Date("2025-04-01") },
    demolition: { status: "未手配" },
    mortgageCancellation: { status: "手配中" },
    registration: { status: "手配中", judicialScrivener: "横浜司法書士" },
    venueArrangement: { status: "手配中" },
    postProcessing: { status: "手配中" },
    isCompleted: false,
    createdAt: new Date("2025-03-01"),
    updatedAt: new Date("2025-03-01"),
  },
  {
    id: "5",
    propertyId: "10",
    propertyNumber: 1475,
    propertyName: "福岡市博多区",
    companyName: "株式会社GHI不動産",
    handlerName: "室橋",
    handlerColor: "#e6f9f3",
    contractDate: new Date("2025-03-15"),
    settlementDate: new Date("2025-07-01"),
    price: 3900,
    estimatedSales: "60/50",
    reform: { status: "手配中", companyName: "博多リノベ", plannedDate: new Date("2025-05-10") },
    loanProcedure: { status: "本申込済", bank: "福岡銀行" },
    survey: { status: "完了", completionDate: new Date("2025-03-25") },
    demolition: { status: "未手配" },
    mortgageCancellation: { status: "手配中" },
    registration: { status: "手配中", judicialScrivener: "福岡法務" },
    venueArrangement: { status: "手配中" },
    postProcessing: { status: "手配中" },
    isCompleted: false,
    createdAt: new Date("2025-03-15"),
    updatedAt: new Date("2025-03-25"),
  },
  {
    id: "6",
    propertyId: "11",
    propertyNumber: 1500,
    propertyName: "札幌市中央区",
    companyName: "株式会社JKL不動産",
    handlerName: "山下",
    handlerColor: "#e6f0fc",
    contractDate: new Date("2025-04-01"),
    settlementDate: new Date("2025-08-15"),
    price: 5200,
    estimatedSales: "90/80",
    reform: { status: "手配中", companyName: "札幌リフォーム", plannedDate: new Date("2025-06-01") },
    loanProcedure: { status: "本申込済", bank: "北海道銀行" },
    survey: { status: "手配中", companyName: "札幌測量", plannedDate: new Date("2025-05-15") },
    demolition: { status: "未手配" },
    mortgageCancellation: { status: "手配中" },
    registration: { status: "手配中", judicialScrivener: "札幌司法書士" },
    venueArrangement: { status: "手配中" },
    postProcessing: { status: "手配中" },
    isCompleted: false,
    createdAt: new Date("2025-04-01"),
    updatedAt: new Date("2025-04-01"),
  },
  {
    id: "7",
    propertyId: "12",
    propertyNumber: 1525,
    propertyName: "仙台市青葉区",
    companyName: "株式会社MNO不動産",
    handlerName: "小道",
    handlerColor: "#f3e6fc",
    contractDate: new Date("2025-04-15"),
    settlementDate: new Date("2025-09-01"),
    price: 4100,
    estimatedSales: "70/60",
    reform: { status: "手配中", companyName: "仙台リノベ", plannedDate: new Date("2025-06-20") },
    loanProcedure: { status: "本申込済", bank: "七十七銀行" },
    survey: { status: "手配中", companyName: "仙台測量", plannedDate: new Date("2025-06-01") },
    demolition: { status: "未手配" },
    mortgageCancellation: { status: "手配中" },
    registration: { status: "手配中", judicialScrivener: "仙台法務" },
    venueArrangement: { status: "手配中" },
    postProcessing: { status: "手配中" },
    isCompleted: false,
    createdAt: new Date("2025-04-15"),
    updatedAt: new Date("2025-04-15"),
  },
  {
    id: "8",
    propertyId: "13",
    propertyNumber: 1550,
    propertyName: "京都市下京区",
    companyName: "株式会社PQR不動産",
    handlerName: "赤堀",
    handlerColor: "#fdcaca",
    contractDate: new Date("2025-05-01"),
    settlementDate: new Date("2025-10-15"),
    price: 7500,
    estimatedSales: "130/110",
    reform: { status: "手配中", companyName: "京都リフォーム", plannedDate: new Date("2025-07-15") },
    loanProcedure: { status: "本申込済", bank: "京都銀行" },
    survey: { status: "手配中", companyName: "京都測量", plannedDate: new Date("2025-06-20") },
    demolition: { status: "未手配" },
    mortgageCancellation: { status: "手配中" },
    registration: { status: "手配中", judicialScrivener: "京都司法書士" },
    venueArrangement: { status: "手配中" },
    postProcessing: { status: "手配中" },
    isCompleted: false,
    createdAt: new Date("2025-05-01"),
    updatedAt: new Date("2025-05-01"),
  },
  {
    id: "9",
    propertyId: "14",
    propertyNumber: 1575,
    propertyName: "神戸市中央区",
    companyName: "株式会社STU不動産",
    handlerName: "室橋",
    handlerColor: "#e6f9f3",
    contractDate: new Date("2025-05-15"),
    settlementDate: new Date("2025-11-01"),
    price: 6300,
    estimatedSales: "110/90",
    reform: { status: "手配中", companyName: "神戸リノベ", plannedDate: new Date("2025-08-01") },
    loanProcedure: { status: "本申込済", bank: "みなと銀行" },
    survey: { status: "手配中", companyName: "神戸測量", plannedDate: new Date("2025-07-10") },
    demolition: { status: "未手配" },
    mortgageCancellation: { status: "手配中" },
    registration: { status: "手配中", judicialScrivener: "神戸法務" },
    venueArrangement: { status: "手配中" },
    postProcessing: { status: "手配中" },
    isCompleted: false,
    createdAt: new Date("2025-05-15"),
    updatedAt: new Date("2025-05-15"),
  },
  {
    id: "10",
    propertyId: "15",
    propertyNumber: 1600,
    propertyName: "広島市中区",
    companyName: "株式会社VWX不動産",
    handlerName: "山下",
    handlerColor: "#e6f0fc",
    contractDate: new Date("2025-06-01"),
    settlementDate: new Date("2025-12-15"),
    price: 4800,
    estimatedSales: "80/70",
    reform: { status: "手配中", companyName: "広島リフォーム", plannedDate: new Date("2025-09-01") },
    loanProcedure: { status: "本申込済", bank: "広島銀行" },
    survey: { status: "手配中", companyName: "広島測量", plannedDate: new Date("2025-08-15") },
    demolition: { status: "未手配" },
    mortgageCancellation: { status: "手配中" },
    registration: { status: "手配中", judicialScrivener: "広島司法書士" },
    venueArrangement: { status: "手配中" },
    postProcessing: { status: "手配中" },
    isCompleted: false,
    createdAt: new Date("2025-06-01"),
    updatedAt: new Date("2025-06-01"),
  },
  {
    id: "11",
    propertyId: "16",
    propertyNumber: 1625,
    propertyName: "金沢市香林坊",
    companyName: "株式会社YZA不動産",
    handlerName: "小道",
    handlerColor: "#f3e6fc",
    contractDate: new Date("2025-01-20"),
    settlementDate: new Date("2025-04-01"),
    price: 3700,
    estimatedSales: "60/50",
    reform: { status: "完了", completionDate: new Date("2025-03-01") },
    loanProcedure: { status: "金商契約済" },
    survey: { status: "完了", completionDate: new Date("2025-02-10") },
    demolition: { status: "未手配" },
    mortgageCancellation: { status: "完了", completionDate: new Date("2025-02-20") },
    registration: { status: "手配中", judicialScrivener: "金沢法務" },
    venueArrangement: { status: "完了" },
    postProcessing: { status: "手配中" },
    isCompleted: false,
    createdAt: new Date("2025-01-20"),
    updatedAt: new Date("2025-03-01"),
  },
  {
    id: "12",
    propertyId: "17",
    propertyNumber: 1650,
    propertyName: "岡山市北区",
    companyName: "株式会社BCD不動産",
    handlerName: "赤堀",
    handlerColor: "#fdcaca",
    contractDate: new Date("2025-02-20"),
    settlementDate: new Date("2025-05-01"),
    price: 4200,
    estimatedSales: "70/60",
    reform: { status: "手配中", companyName: "岡山リノベ", plannedDate: new Date("2025-04-01") },
    loanProcedure: { status: "本申込済", bank: "中国銀行" },
    survey: { status: "完了", completionDate: new Date("2025-03-05") },
    demolition: { status: "未手配" },
    mortgageCancellation: { status: "手配中" },
    registration: { status: "手配中", judicialScrivener: "岡山司法書士" },
    venueArrangement: { status: "手配中" },
    postProcessing: { status: "手配中" },
    isCompleted: false,
    createdAt: new Date("2025-02-20"),
    updatedAt: new Date("2025-03-05"),
  },
  {
    id: "13",
    propertyId: "18",
    propertyNumber: 1675,
    propertyName: "熊本市中央区",
    companyName: "株式会社EFG不動産",
    handlerName: "室橋",
    handlerColor: "#e6f9f3",
    contractDate: new Date("2025-03-20"),
    settlementDate: new Date("2025-07-15"),
    price: 3500,
    estimatedSales: "55/45",
    reform: { status: "手配中", companyName: "熊本リフォーム", plannedDate: new Date("2025-05-20") },
    loanProcedure: { status: "本申込済", bank: "肥後銀行" },
    survey: { status: "手配中", companyName: "熊本測量", plannedDate: new Date("2025-05-01") },
    demolition: { status: "未手配" },
    mortgageCancellation: { status: "手配中" },
    registration: { status: "手配中", judicialScrivener: "熊本法務" },
    venueArrangement: { status: "手配中" },
    postProcessing: { status: "手配中" },
    isCompleted: false,
    createdAt: new Date("2025-03-20"),
    updatedAt: new Date("2025-03-20"),
  },
  {
    id: "14",
    propertyId: "19",
    propertyNumber: 1700,
    propertyName: "鹿児島市中央町",
    companyName: "株式会社HIJ不動産",
    handlerName: "山下",
    handlerColor: "#e6f0fc",
    contractDate: new Date("2025-04-20"),
    settlementDate: new Date("2025-09-15"),
    price: 3200,
    estimatedSales: "50/40",
    reform: { status: "手配中", companyName: "鹿児島リノベ", plannedDate: new Date("2025-07-01") },
    loanProcedure: { status: "本申込済", bank: "鹿児島銀行" },
    survey: { status: "手配中", companyName: "鹿児島測量", plannedDate: new Date("2025-06-15") },
    demolition: { status: "未手配" },
    mortgageCancellation: { status: "手配中" },
    registration: { status: "手配中", judicialScrivener: "鹿児島司法書士" },
    venueArrangement: { status: "手配中" },
    postProcessing: { status: "手配中" },
    isCompleted: false,
    createdAt: new Date("2025-04-20"),
    updatedAt: new Date("2025-04-20"),
  },
  {
    id: "15",
    propertyId: "20",
    propertyNumber: 1725,
    propertyName: "那覇市久茂地",
    companyName: "株式会社KLM不動産",
    handlerName: "小道",
    handlerColor: "#f3e6fc",
    contractDate: new Date("2025-05-20"),
    settlementDate: new Date("2025-11-15"),
    price: 5500,
    estimatedSales: "95/85",
    reform: { status: "手配中", companyName: "沖縄リフォーム", plannedDate: new Date("2025-08-15") },
    loanProcedure: { status: "本申込済", bank: "琉球銀行" },
    survey: { status: "手配中", companyName: "沖縄測量", plannedDate: new Date("2025-07-20") },
    demolition: { status: "未手配" },
    mortgageCancellation: { status: "手配中" },
    registration: { status: "手配中", judicialScrivener: "那覇法務" },
    venueArrangement: { status: "手配中" },
    postProcessing: { status: "手配中" },
    isCompleted: false,
    createdAt: new Date("2025-05-20"),
    updatedAt: new Date("2025-05-20"),
  },
]

export const MOCK_USERS: (User & { password: string })[] = [
  {
    id: "1",
    email: "admin@example.com",
    password: "admin123",
    name: "管理者",
    role: "admin",
    color: "#94a3b8", // 管理者用のグレー
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "2",
    email: "user@example.com",
    password: "user123",
    name: "一般ユーザー",
    role: "user",
    color: "#60a5fa", // ユーザー用の青
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
]

// Helper function to get unique handlers
export function getUniqueHandlers(properties: Property[]): string[] {
  return Array.from(new Set(properties.map((p) => p.handlerName))).sort()
}

export function calculateTaskProgress(task: PropertyTask): number {
  const taskFields: (keyof PropertyTask)[] = [
    "reform",
    "loanProcedure",
    "survey",
    "demolition",
    "mortgageCancellation",
    "registration",
    "venueArrangement",
    // postProcessing は進捗計算に含めない
  ]

  const completedStatuses = ["完了", "不要", "金商契約済", "手配済（決済場所も手配済）"]

  const completedTasks = taskFields.filter((field) => {
    const taskDetail = task[field] as TaskDetail | undefined
    if (!taskDetail || typeof taskDetail !== "object" || !("status" in taskDetail)) {
      return false
    }
    return completedStatuses.includes(taskDetail.status as string)
  }).length

  // The contract itself is a completed step.
  const contractCompleted = 1
  const totalSteps = taskFields.length + contractCompleted
  const completedSteps = completedTasks + contractCompleted

  return Math.floor((completedSteps / totalSteps) * 100)
}

export function getHandlerColor(handlerName: string): string {
  const handler = MOCK_HANDLERS.find((h) => h.name === handlerName)
  return handler?.color || "#f3f4f6"
}
